services: 
"  - type: web" 
"    name: benfarming" 
"    env: python" 
"    region: oregon" 
"    buildCommand: pip install -r requirements.txt" 
"    startCommand: gunicorn app:app" 
"    envVars:" 
"      - key: FLASK_DEBUG" 
"        value: false" 
"      - key: SECRET_KEY" 
"        sync: false" 
"      - key: DATABASE_URL" 
"        fromDatabase:" 
"          name: benfarming-db" 
"          property: connectionString" 
"" 
databases: 
"  - name: benfarming-db" 
"    databaseName: benfarming" 
"    plan: free" 
"    region: oregon" 
